import { db } from '@/db';
import { bookings } from '@/db/schema';

async function main() {
    const sampleBookings = [
        // Active bookings (8) - Current residents
        {
            userId: 3,
            propertyId: 5,
            roomTypeId: 12,
            moveInDate: new Date('2024-08-15').toISOString(),
            durationMonths: 12,
            totalAmount: 120000,
            bookingAmountPaid: 20000,
            status: 'Active',
            paymentStatus: 'Paid',
            nextRentDueDate: new Date('2025-03-01').toISOString(),
            bookingConfirmationUrl: 'https://example.com/receipt/1.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-08-10').toISOString(),
        },
        {
            userId: 7,
            propertyId: 12,
            roomTypeId: 34,
            moveInDate: new Date('2024-09-01').toISOString(),
            durationMonths: 6,
            totalAmount: 72000,
            bookingAmountPaid: 24000,
            status: 'Active',
            paymentStatus: 'Paid',
            nextRentDueDate: new Date('2025-03-01').toISOString(),
            bookingConfirmationUrl: 'https://example.com/receipt/2.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-08-25').toISOString(),
        },
        {
            userId: 12,
            propertyId: 18,
            roomTypeId: 45,
            moveInDate: new Date('2024-10-15').toISOString(),
            durationMonths: 12,
            totalAmount: 180000,
            bookingAmountPaid: 30000,
            status: 'Active',
            paymentStatus: 'Due',
            nextRentDueDate: new Date('2025-02-15').toISOString(),
            bookingConfirmationUrl: 'https://example.com/receipt/3.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-10-10').toISOString(),
        },
        {
            userId: 5,
            propertyId: 8,
            roomTypeId: 22,
            moveInDate: new Date('2024-11-01').toISOString(),
            durationMonths: 3,
            totalAmount: 33000,
            bookingAmountPaid: 22000,
            status: 'Active',
            paymentStatus: 'Paid',
            nextRentDueDate: new Date('2025-02-01').toISOString(),
            bookingConfirmationUrl: 'https://example.com/receipt/4.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-10-28').toISOString(),
        },
        {
            userId: 14,
            propertyId: 22,
            roomTypeId: 58,
            moveInDate: new Date('2024-09-20').toISOString(),
            durationMonths: 6,
            totalAmount: 78000,
            bookingAmountPaid: 26000,
            status: 'Active',
            paymentStatus: 'Paid',
            nextRentDueDate: new Date('2025-03-20').toISOString(),
            bookingConfirmationUrl: 'https://example.com/receipt/5.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-09-15').toISOString(),
        },
        {
            userId: 9,
            propertyId: 15,
            roomTypeId: 41,
            moveInDate: new Date('2024-08-01').toISOString(),
            durationMonths: 12,
            totalAmount: 144000,
            bookingAmountPaid: 24000,
            status: 'Active',
            paymentStatus: 'Due',
            nextRentDueDate: new Date('2025-02-01').toISOString(),
            bookingConfirmationUrl: 'https://example.com/receipt/6.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-07-25').toISOString(),
        },
        {
            userId: 2,
            propertyId: 7,
            roomTypeId: 19,
            moveInDate: new Date('2024-10-01').toISOString(),
            durationMonths: 6,
            totalAmount: 66000,
            bookingAmountPaid: 22000,
            status: 'Active',
            paymentStatus: 'Paid',
            nextRentDueDate: new Date('2025-04-01').toISOString(),
            bookingConfirmationUrl: 'https://example.com/receipt/7.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-09-25').toISOString(),
        },
        {
            userId: 11,
            propertyId: 20,
            roomTypeId: 52,
            moveInDate: new Date('2024-11-15').toISOString(),
            durationMonths: 3,
            totalAmount: 36000,
            bookingAmountPaid: 24000,
            status: 'Active',
            paymentStatus: 'Paid',
            nextRentDueDate: new Date('2025-02-15').toISOString(),
            bookingConfirmationUrl: 'https://example.com/receipt/8.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-11-10').toISOString(),
        },
        
        // Upcoming bookings (5) - Move-in date in future
        {
            userId: 6,
            propertyId: 10,
            roomTypeId: 28,
            moveInDate: new Date('2025-02-15').toISOString(),
            durationMonths: 12,
            totalAmount: 156000,
            bookingAmountPaid: 26000,
            status: 'Upcoming',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/9.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2025-01-10').toISOString(),
        },
        {
            userId: 13,
            propertyId: 24,
            roomTypeId: 63,
            moveInDate: new Date('2025-03-01').toISOString(),
            durationMonths: 6,
            totalAmount: 84000,
            bookingAmountPaid: 28000,
            status: 'Upcoming',
            paymentStatus: 'Pending',
            nextRentDueDate: null,
            bookingConfirmationUrl: null,
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2025-01-15').toISOString(),
        },
        {
            userId: 4,
            propertyId: 3,
            roomTypeId: 8,
            moveInDate: new Date('2025-02-20').toISOString(),
            durationMonths: 3,
            totalAmount: 30000,
            bookingAmountPaid: 20000,
            status: 'Upcoming',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/11.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2025-01-18').toISOString(),
        },
        {
            userId: 15,
            propertyId: 17,
            roomTypeId: 46,
            moveInDate: new Date('2025-03-10').toISOString(),
            durationMonths: 12,
            totalAmount: 168000,
            bookingAmountPaid: 28000,
            status: 'Upcoming',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/12.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2025-01-20').toISOString(),
        },
        {
            userId: 8,
            propertyId: 14,
            roomTypeId: 38,
            moveInDate: new Date('2025-02-25').toISOString(),
            durationMonths: 6,
            totalAmount: 72000,
            bookingAmountPaid: 24000,
            status: 'Upcoming',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/13.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2025-01-22').toISOString(),
        },
        
        // Past bookings (5) - Completed stays
        {
            userId: 10,
            propertyId: 9,
            roomTypeId: 25,
            moveInDate: new Date('2023-12-01').toISOString(),
            durationMonths: 12,
            totalAmount: 132000,
            bookingAmountPaid: 22000,
            status: 'Past',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/14.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2023-11-25').toISOString(),
        },
        {
            userId: 1,
            propertyId: 6,
            roomTypeId: 16,
            moveInDate: new Date('2024-01-15').toISOString(),
            durationMonths: 6,
            totalAmount: 60000,
            bookingAmountPaid: 20000,
            status: 'Past',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/15.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            userId: 5,
            propertyId: 13,
            roomTypeId: 35,
            moveInDate: new Date('2023-10-01').toISOString(),
            durationMonths: 3,
            totalAmount: 39000,
            bookingAmountPaid: 26000,
            status: 'Past',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/16.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2023-09-25').toISOString(),
        },
        {
            userId: 14,
            propertyId: 21,
            roomTypeId: 55,
            moveInDate: new Date('2024-02-01').toISOString(),
            durationMonths: 6,
            totalAmount: 66000,
            bookingAmountPaid: 22000,
            status: 'Past',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/17.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            userId: 3,
            propertyId: 11,
            roomTypeId: 31,
            moveInDate: new Date('2023-11-15').toISOString(),
            durationMonths: 12,
            totalAmount: 150000,
            bookingAmountPaid: 25000,
            status: 'Past',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/18.pdf',
            cancellationDate: null,
            refundStatus: null,
            refundAmount: null,
            createdAt: new Date('2023-11-10').toISOString(),
        },
        
        // Cancelled bookings (2) - Cancelled with refund info
        {
            userId: 7,
            propertyId: 16,
            roomTypeId: 43,
            moveInDate: new Date('2025-01-20').toISOString(),
            durationMonths: 6,
            totalAmount: 78000,
            bookingAmountPaid: 26000,
            status: 'Cancelled',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/19.pdf',
            cancellationDate: new Date('2025-01-10').toISOString(),
            refundStatus: 'Processed',
            refundAmount: 23400,
            createdAt: new Date('2024-12-20').toISOString(),
        },
        {
            userId: 12,
            propertyId: 25,
            roomTypeId: 68,
            moveInDate: new Date('2025-02-10').toISOString(),
            durationMonths: 12,
            totalAmount: 180000,
            bookingAmountPaid: 30000,
            status: 'Cancelled',
            paymentStatus: 'Paid',
            nextRentDueDate: null,
            bookingConfirmationUrl: 'https://example.com/receipt/20.pdf',
            cancellationDate: new Date('2025-01-12').toISOString(),
            refundStatus: 'Pending',
            refundAmount: 27000,
            createdAt: new Date('2024-12-28').toISOString(),
        },
    ];

    await db.insert(bookings).values(sampleBookings);
    
    console.log('✅ Bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});