import { db } from '@/db';
import { payments } from '@/db/schema';

async function main() {
    const samplePayments = [
        // Booking Payments (20 records)
        {
            userId: 1,
            bookingId: 1,
            amount: 15000,
            paymentType: 'booking',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240115ABC123',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/1.pdf',
            createdAt: new Date('2024-01-15T10:30:00').toISOString(),
        },
        {
            userId: 2,
            bookingId: 2,
            amount: 25000,
            paymentType: 'booking',
            paymentMethod: 'Card',
            transactionId: 'CRD20240116XYZ456',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/2.pdf',
            createdAt: new Date('2024-01-16T14:20:00').toISOString(),
        },
        {
            userId: 3,
            bookingId: 3,
            amount: 18000,
            paymentType: 'booking',
            paymentMethod: 'NetBanking',
            transactionId: 'NB20240117DEF789',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/3.pdf',
            createdAt: new Date('2024-01-17T09:15:00').toISOString(),
        },
        {
            userId: 4,
            bookingId: 4,
            amount: 12000,
            paymentType: 'booking',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240118GHI012',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/4.pdf',
            createdAt: new Date('2024-01-18T11:45:00').toISOString(),
        },
        {
            userId: 5,
            bookingId: 5,
            amount: 22000,
            paymentType: 'booking',
            paymentMethod: 'Card',
            transactionId: 'CRD20240119JKL345',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/5.pdf',
            createdAt: new Date('2024-01-19T16:30:00').toISOString(),
        },
        {
            userId: 6,
            bookingId: 6,
            amount: 8000,
            paymentType: 'booking',
            paymentMethod: 'Wallet',
            transactionId: 'WLT20240120MNO678',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/6.pdf',
            createdAt: new Date('2024-01-20T13:00:00').toISOString(),
        },
        {
            userId: 7,
            bookingId: 7,
            amount: 30000,
            paymentType: 'booking',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240121PQR901',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/7.pdf',
            createdAt: new Date('2024-01-21T10:00:00').toISOString(),
        },
        {
            userId: 8,
            bookingId: 8,
            amount: 16000,
            paymentType: 'booking',
            paymentMethod: 'NetBanking',
            transactionId: 'NB20240122STU234',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/8.pdf',
            createdAt: new Date('2024-01-22T15:20:00').toISOString(),
        },
        {
            userId: 9,
            bookingId: 9,
            amount: 20000,
            paymentType: 'booking',
            paymentMethod: 'Card',
            transactionId: 'CRD20240123VWX567',
            status: 'pending',
            invoiceUrl: null,
            createdAt: new Date('2024-01-23T12:10:00').toISOString(),
        },
        {
            userId: 10,
            bookingId: 10,
            amount: 14000,
            paymentType: 'booking',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240124YZA890',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/10.pdf',
            createdAt: new Date('2024-01-24T09:30:00').toISOString(),
        },
        {
            userId: 11,
            bookingId: 11,
            amount: 27000,
            paymentType: 'booking',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240125BCD123',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/11.pdf',
            createdAt: new Date('2024-01-25T14:45:00').toISOString(),
        },
        {
            userId: 12,
            bookingId: 12,
            amount: 11000,
            paymentType: 'booking',
            paymentMethod: 'Card',
            transactionId: 'CRD20240126EFG456',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/12.pdf',
            createdAt: new Date('2024-01-26T11:20:00').toISOString(),
        },
        {
            userId: 13,
            bookingId: 13,
            amount: 19000,
            paymentType: 'booking',
            paymentMethod: 'NetBanking',
            transactionId: 'NB20240127HIJ789',
            status: 'failed',
            invoiceUrl: null,
            createdAt: new Date('2024-01-27T16:00:00').toISOString(),
        },
        {
            userId: 14,
            bookingId: 14,
            amount: 23000,
            paymentType: 'booking',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240128KLM012',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/14.pdf',
            createdAt: new Date('2024-01-28T10:15:00').toISOString(),
        },
        {
            userId: 15,
            bookingId: 15,
            amount: 17000,
            paymentType: 'booking',
            paymentMethod: 'Wallet',
            transactionId: 'WLT20240129NOP345',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/15.pdf',
            createdAt: new Date('2024-01-29T13:40:00').toISOString(),
        },
        {
            userId: 1,
            bookingId: 16,
            amount: 21000,
            paymentType: 'booking',
            paymentMethod: 'Card',
            transactionId: 'CRD20240130QRS678',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/16.pdf',
            createdAt: new Date('2024-01-30T15:25:00').toISOString(),
        },
        {
            userId: 3,
            bookingId: 17,
            amount: 13000,
            paymentType: 'booking',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240131TUV901',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/17.pdf',
            createdAt: new Date('2024-01-31T09:50:00').toISOString(),
        },
        {
            userId: 5,
            bookingId: 18,
            amount: 28000,
            paymentType: 'booking',
            paymentMethod: 'NetBanking',
            transactionId: 'NB20240201WXY234',
            status: 'pending',
            invoiceUrl: null,
            createdAt: new Date('2024-02-01T12:00:00').toISOString(),
        },
        {
            userId: 7,
            bookingId: 19,
            amount: 9000,
            paymentType: 'booking',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240202ZAB567',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/19.pdf',
            createdAt: new Date('2024-02-02T14:30:00').toISOString(),
        },
        {
            userId: 9,
            bookingId: 20,
            amount: 26000,
            paymentType: 'booking',
            paymentMethod: 'Card',
            transactionId: 'CRD20240203CDE890',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/20.pdf',
            createdAt: new Date('2024-02-03T11:15:00').toISOString(),
        },
        // Rent Payments (8 records)
        {
            userId: 1,
            bookingId: 1,
            amount: 12000,
            paymentType: 'rent',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240215FGH123',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/21.pdf',
            createdAt: new Date('2024-02-15T10:00:00').toISOString(),
        },
        {
            userId: 2,
            bookingId: 2,
            amount: 18000,
            paymentType: 'rent',
            paymentMethod: 'Card',
            transactionId: 'CRD20240216IJK456',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/22.pdf',
            createdAt: new Date('2024-02-16T11:30:00').toISOString(),
        },
        {
            userId: 4,
            bookingId: 4,
            amount: 10000,
            paymentType: 'rent',
            paymentMethod: 'NetBanking',
            transactionId: 'NB20240217LMN789',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/23.pdf',
            createdAt: new Date('2024-02-17T09:45:00').toISOString(),
        },
        {
            userId: 5,
            bookingId: 5,
            amount: 15000,
            paymentType: 'rent',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240218OPQ012',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/24.pdf',
            createdAt: new Date('2024-02-18T14:20:00').toISOString(),
        },
        {
            userId: 7,
            bookingId: 7,
            amount: 25000,
            paymentType: 'rent',
            paymentMethod: 'Card',
            transactionId: 'CRD20240219RST345',
            status: 'pending',
            invoiceUrl: null,
            createdAt: new Date('2024-02-19T16:10:00').toISOString(),
        },
        {
            userId: 8,
            bookingId: 8,
            amount: 13000,
            paymentType: 'rent',
            paymentMethod: 'UPI',
            transactionId: 'UPI20240220UVW678',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/26.pdf',
            createdAt: new Date('2024-02-20T10:30:00').toISOString(),
        },
        {
            userId: 10,
            bookingId: 10,
            amount: 11000,
            paymentType: 'rent',
            paymentMethod: 'Wallet',
            transactionId: 'WLT20240221XYZ901',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/27.pdf',
            createdAt: new Date('2024-02-21T13:15:00').toISOString(),
        },
        {
            userId: 11,
            bookingId: 11,
            amount: 20000,
            paymentType: 'rent',
            paymentMethod: 'NetBanking',
            transactionId: 'NB20240222ABC234',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/28.pdf',
            createdAt: new Date('2024-02-22T15:45:00').toISOString(),
        },
        // Refund Payments (2 records)
        {
            userId: 6,
            bookingId: 6,
            amount: 8000,
            paymentType: 'refund',
            paymentMethod: 'UPI',
            transactionId: 'RFND20240225DEF567',
            status: 'success',
            invoiceUrl: 'https://example.com/invoice/29.pdf',
            createdAt: new Date('2024-02-25T11:00:00').toISOString(),
        },
        {
            userId: 13,
            bookingId: 13,
            amount: 15000,
            paymentType: 'refund',
            paymentMethod: 'NetBanking',
            transactionId: 'RFND20240226GHI890',
            status: 'pending',
            invoiceUrl: null,
            createdAt: new Date('2024-02-26T14:30:00').toISOString(),
        },
    ];

    await db.insert(payments).values(samplePayments);
    
    console.log('✅ Payments seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});