import { db } from '@/db';
import { properties } from '@/db/schema';

async function main() {
    const sampleProperties = [
        // Mumbai Properties (6)
        {
            name: 'Sunrise PG Andheri',
            description: 'Modern PG accommodation with all amenities in prime Andheri location. Close to metro station and shopping centers.',
            address: 'Plot No. 42, Veera Desai Road, Andheri West, Mumbai, Maharashtra 400053',
            city: 'Mumbai',
            locality: 'Andheri West',
            latitude: 19.1367,
            longitude: 72.8269,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365'
            ]),
            startingPrice: 12000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Parking']),
            virtualTourUrl: 'https://example.com/virtual-tour/1',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543210',
            managerName: 'Rajesh Kumar',
            rating: 4.5,
            totalReviews: 67,
            isAvailable: true,
            createdAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Elite Residency Bandra',
            description: 'Premium PG for working professionals with gym and rooftop terrace. Walking distance from Bandra station.',
            address: '15th Road, Khar West, Bandra, Mumbai, Maharashtra 400052',
            city: 'Mumbai',
            locality: 'Bandra West',
            latitude: 19.0596,
            longitude: 72.8295,
            genderType: 'Female',
            thumbnailImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1'
            ]),
            startingPrice: 18000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Gym', 'Laundry', 'Parking', 'Balcony']),
            virtualTourUrl: 'https://example.com/virtual-tour/2',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543211',
            managerName: 'Priya Sharma',
            rating: 4.8,
            totalReviews: 89,
            isAvailable: true,
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Urban Nest Powai',
            description: 'Spacious PG near Hiranandani Gardens with lake view rooms. Ideal for IT professionals.',
            address: 'Central Avenue, Hiranandani Gardens, Powai, Mumbai, Maharashtra 400076',
            city: 'Mumbai',
            locality: 'Powai',
            latitude: 19.1176,
            longitude: 72.9060,
            genderType: 'Unisex',
            thumbnailImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1'
            ]),
            startingPrice: 15000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Parking', 'Balcony']),
            virtualTourUrl: null,
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543212',
            managerName: 'Amit Patel',
            rating: 4.3,
            totalReviews: 54,
            isAvailable: true,
            createdAt: new Date('2024-03-05').toISOString(),
        },
        {
            name: 'Comfort Zone PG Goregaon',
            description: 'Budget-friendly PG with home-cooked meals. Close to film city and commercial areas.',
            address: 'Link Road, Goregaon East, Mumbai, Maharashtra 400063',
            city: 'Mumbai',
            locality: 'Goregaon East',
            latitude: 19.1663,
            longitude: 72.8526,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1540518614846-7eded433c457',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1'
            ]),
            startingPrice: 9000,
            amenities: JSON.stringify(['WiFi', 'Food', 'Laundry']),
            virtualTourUrl: null,
            cancellationPolicy: 'Non-refundable',
            refundPolicy: 'No refund',
            managerPhone: '+919876543213',
            managerName: 'Sanjay Desai',
            rating: 4.0,
            totalReviews: 42,
            isAvailable: true,
            createdAt: new Date('2024-04-20').toISOString(),
        },
        {
            name: 'Green Valley PG Thane',
            description: 'Peaceful PG in green surroundings with spacious rooms and terrace garden.',
            address: 'Ghodbunder Road, Thane West, Mumbai, Maharashtra 400607',
            city: 'Mumbai',
            locality: 'Thane West',
            latitude: 19.2183,
            longitude: 72.9781,
            genderType: 'Female',
            thumbnailImage: 'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af'
            ]),
            startingPrice: 11000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Balcony']),
            virtualTourUrl: 'https://example.com/virtual-tour/5',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543214',
            managerName: 'Neha Joshi',
            rating: 4.6,
            totalReviews: 73,
            isAvailable: true,
            createdAt: new Date('2024-02-28').toISOString(),
        },
        {
            name: 'Professional Paradise Malad',
            description: 'Corporate PG with conference room and co-working space. Perfect for remote workers.',
            address: 'Marve Road, Malad West, Mumbai, Maharashtra 400064',
            city: 'Mumbai',
            locality: 'Malad West',
            latitude: 19.1866,
            longitude: 72.8356,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2'
            ]),
            startingPrice: 16000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Gym', 'Laundry', 'Parking']),
            virtualTourUrl: 'https://example.com/virtual-tour/6',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543215',
            managerName: 'Vikram Singh',
            rating: 4.7,
            totalReviews: 81,
            isAvailable: true,
            createdAt: new Date('2024-01-25').toISOString(),
        },

        // Delhi Properties (5)
        {
            name: 'Student Hub Karol Bagh',
            description: 'Popular PG among students and young professionals. Near metro station and coaching centers.',
            address: 'Arya Samaj Road, Karol Bagh, New Delhi, Delhi 110005',
            city: 'Delhi',
            locality: 'Karol Bagh',
            latitude: 28.6517,
            longitude: 77.1905,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2'
            ]),
            startingPrice: 10000,
            amenities: JSON.stringify(['WiFi', 'Food', 'Laundry', 'Parking']),
            virtualTourUrl: null,
            cancellationPolicy: 'Non-refundable',
            refundPolicy: 'No refund',
            managerPhone: '+919876543216',
            managerName: 'Ravi Verma',
            rating: 4.2,
            totalReviews: 58,
            isAvailable: true,
            createdAt: new Date('2024-03-12').toISOString(),
        },
        {
            name: 'Royal Residency Rajouri Garden',
            description: 'Luxurious PG with modern amenities and 24/7 security. Close to DU colleges.',
            address: 'Tagore Garden Extension, Rajouri Garden, New Delhi, Delhi 110027',
            city: 'Delhi',
            locality: 'Rajouri Garden',
            latitude: 28.6418,
            longitude: 77.1178,
            genderType: 'Female',
            thumbnailImage: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457'
            ]),
            startingPrice: 14000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Gym', 'Parking']),
            virtualTourUrl: 'https://example.com/virtual-tour/8',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543217',
            managerName: 'Pooja Kapoor',
            rating: 4.5,
            totalReviews: 92,
            isAvailable: true,
            createdAt: new Date('2024-02-08').toISOString(),
        },
        {
            name: 'Metro View PG Laxmi Nagar',
            description: 'Budget PG near Laxmi Nagar metro with easy access to Noida and Ghaziabad.',
            address: 'Vikas Marg, Laxmi Nagar, East Delhi, Delhi 110092',
            city: 'Delhi',
            locality: 'Laxmi Nagar',
            latitude: 28.6359,
            longitude: 77.2768,
            genderType: 'Unisex',
            thumbnailImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457'
            ]),
            startingPrice: 8000,
            amenities: JSON.stringify(['WiFi', 'Food', 'Laundry']),
            virtualTourUrl: null,
            cancellationPolicy: 'Non-refundable',
            refundPolicy: 'No refund',
            managerPhone: '+919876543218',
            managerName: 'Suresh Kumar',
            rating: 3.8,
            totalReviews: 35,
            isAvailable: true,
            createdAt: new Date('2024-04-15').toISOString(),
        },
        {
            name: 'Executive Towers Connaught Place',
            description: 'Premium PG in heart of Delhi with rooftop cafe and business lounge.',
            address: 'Barakhamba Road, Connaught Place, New Delhi, Delhi 110001',
            city: 'Delhi',
            locality: 'Connaught Place',
            latitude: 28.6315,
            longitude: 77.2167,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1'
            ]),
            startingPrice: 22000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Gym', 'Laundry', 'Parking', 'Balcony']),
            virtualTourUrl: 'https://example.com/virtual-tour/10',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543219',
            managerName: 'Arun Malhotra',
            rating: 4.9,
            totalReviews: 98,
            isAvailable: true,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Comfort Living Dwarka',
            description: 'Spacious PG in Dwarka sector 7 with family-like environment and home food.',
            address: 'Sector 7, Dwarka, South West Delhi, Delhi 110075',
            city: 'Delhi',
            locality: 'Dwarka',
            latitude: 28.5921,
            longitude: 77.0460,
            genderType: 'Female',
            thumbnailImage: 'https://images.unsplash.com/photo-1540518614846-7eded433c457',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1'
            ]),
            startingPrice: 11000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Parking']),
            virtualTourUrl: null,
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543220',
            managerName: 'Meena Gupta',
            rating: 4.4,
            totalReviews: 66,
            isAvailable: true,
            createdAt: new Date('2024-03-22').toISOString(),
        },

        // Bangalore Properties (6)
        {
            name: 'Tech Hub PG Koramangala',
            description: 'Modern PG in startup hub with high-speed internet and co-working space.',
            address: '5th Block, Koramangala, Bangalore, Karnataka 560095',
            city: 'Bangalore',
            locality: 'Koramangala',
            latitude: 12.9352,
            longitude: 77.6245,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5'
            ]),
            startingPrice: 15000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Gym', 'Parking']),
            virtualTourUrl: 'https://example.com/virtual-tour/12',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543221',
            managerName: 'Karthik Reddy',
            rating: 4.6,
            totalReviews: 87,
            isAvailable: true,
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Garden View PG Whitefield',
            description: 'Peaceful PG near IT parks with garden and outdoor seating area.',
            address: 'ITPL Main Road, Whitefield, Bangalore, Karnataka 560066',
            city: 'Bangalore',
            locality: 'Whitefield',
            latitude: 12.9698,
            longitude: 77.7499,
            genderType: 'Female',
            thumbnailImage: 'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5'
            ]),
            startingPrice: 13000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Parking', 'Balcony']),
            virtualTourUrl: 'https://example.com/virtual-tour/13',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543222',
            managerName: 'Lakshmi Narayan',
            rating: 4.5,
            totalReviews: 71,
            isAvailable: true,
            createdAt: new Date('2024-03-01').toISOString(),
        },
        {
            name: 'Silicon Valley Residency BTM',
            description: 'Premium PG near Silk Board with gym and swimming pool access.',
            address: '2nd Stage, BTM Layout, Bangalore, Karnataka 560076',
            city: 'Bangalore',
            locality: 'BTM Layout',
            latitude: 12.9165,
            longitude: 77.6101,
            genderType: 'Unisex',
            thumbnailImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267'
            ]),
            startingPrice: 17000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Gym', 'Laundry', 'Parking', 'Balcony']),
            virtualTourUrl: 'https://example.com/virtual-tour/14',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543223',
            managerName: 'Suresh Babu',
            rating: 4.7,
            totalReviews: 94,
            isAvailable: true,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Budget Stays Marathahalli',
            description: 'Affordable PG for students and working professionals near Marathahalli bridge.',
            address: 'Outer Ring Road, Marathahalli, Bangalore, Karnataka 560037',
            city: 'Bangalore',
            locality: 'Marathahalli',
            latitude: 12.9591,
            longitude: 77.6974,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267'
            ]),
            startingPrice: 9000,
            amenities: JSON.stringify(['WiFi', 'Food', 'Laundry']),
            virtualTourUrl: null,
            cancellationPolicy: 'Non-refundable',
            refundPolicy: 'No refund',
            managerPhone: '+919876543224',
            managerName: 'Ramesh Kumar',
            rating: 3.9,
            totalReviews: 48,
            isAvailable: true,
            createdAt: new Date('2024-04-05').toISOString(),
        },
        {
            name: 'Elite Living HSR Layout',
            description: 'Upscale PG with modern interiors and premium amenities in HSR Layout Sector 1.',
            address: '27th Main Road, Sector 1, HSR Layout, Bangalore, Karnataka 560102',
            city: 'Bangalore',
            locality: 'HSR Layout',
            latitude: 12.9121,
            longitude: 77.6446,
            genderType: 'Female',
            thumbnailImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365'
            ]),
            startingPrice: 16000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Gym', 'Laundry', 'Parking', 'Balcony']),
            virtualTourUrl: 'https://example.com/virtual-tour/17',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543225',
            managerName: 'Anjali Rao',
            rating: 4.8,
            totalReviews: 85,
            isAvailable: true,
            createdAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Smart Stay Indiranagar',
            description: 'Trendy PG in vibrant Indiranagar with rooftop cafe and entertainment area.',
            address: '100 Feet Road, Indiranagar, Bangalore, Karnataka 560038',
            city: 'Bangalore',
            locality: 'Indiranagar',
            latitude: 12.9716,
            longitude: 77.6412,
            genderType: 'Unisex',
            thumbnailImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365'
            ]),
            startingPrice: 18000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Gym', 'Parking']),
            virtualTourUrl: 'https://example.com/virtual-tour/18',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543226',
            managerName: 'Vivek Sharma',
            rating: 4.6,
            totalReviews: 79,
            isAvailable: true,
            createdAt: new Date('2024-01-30').toISOString(),
        },

        // Pune Properties (4)
        {
            name: 'Harmony PG Viman Nagar',
            description: 'Well-maintained PG near Pune Airport with 24/7 water and power backup.',
            address: 'Nagar Road, Viman Nagar, Pune, Maharashtra 411014',
            city: 'Pune',
            locality: 'Viman Nagar',
            latitude: 18.5679,
            longitude: 73.9143,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1540518614846-7eded433c457',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1'
            ]),
            startingPrice: 11000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Parking']),
            virtualTourUrl: null,
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543227',
            managerName: 'Mahesh Patil',
            rating: 4.3,
            totalReviews: 62,
            isAvailable: true,
            createdAt: new Date('2024-03-10').toISOString(),
        },
        {
            name: 'Purple Pearl PG Kothrud',
            description: 'Ladies PG in peaceful Kothrud area with strict security and homely atmosphere.',
            address: 'Karve Road, Kothrud, Pune, Maharashtra 411038',
            city: 'Pune',
            locality: 'Kothrud',
            latitude: 18.5074,
            longitude: 73.8077,
            genderType: 'Female',
            thumbnailImage: 'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5'
            ]),
            startingPrice: 12000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Balcony']),
            virtualTourUrl: 'https://example.com/virtual-tour/20',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543228',
            managerName: 'Sunita Deshmukh',
            rating: 4.7,
            totalReviews: 76,
            isAvailable: true,
            createdAt: new Date('2024-02-18').toISOString(),
        },
        {
            name: 'Phoenix Residency Hinjewadi',
            description: 'Corporate PG near IT parks with shuttle service to Rajiv Gandhi Infotech Park.',
            address: 'Phase 1, Hinjewadi, Pune, Maharashtra 411057',
            city: 'Pune',
            locality: 'Hinjewadi',
            latitude: 18.5912,
            longitude: 73.7389,
            genderType: 'Unisex',
            thumbnailImage: 'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5'
            ]),
            startingPrice: 14000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Gym', 'Laundry', 'Parking']),
            virtualTourUrl: 'https://example.com/virtual-tour/21',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543229',
            managerName: 'Nitin Joshi',
            rating: 4.5,
            totalReviews: 68,
            isAvailable: true,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Campus Corner PG Wakad',
            description: 'Student-friendly PG near colleges with study room and recreational facilities.',
            address: 'Mumbai-Bangalore Highway, Wakad, Pune, Maharashtra 411057',
            city: 'Pune',
            locality: 'Wakad',
            latitude: 18.5988,
            longitude: 73.7683,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2'
            ]),
            startingPrice: 10000,
            amenities: JSON.stringify(['WiFi', 'Food', 'Laundry', 'Parking']),
            virtualTourUrl: null,
            cancellationPolicy: 'Non-refundable',
            refundPolicy: 'No refund',
            managerPhone: '+919876543230',
            managerName: 'Rajesh Kulkarni',
            rating: 4.1,
            totalReviews: 53,
            isAvailable: true,
            createdAt: new Date('2024-04-01').toISOString(),
        },

        // Hyderabad Properties (4)
        {
            name: 'Cyber Pearl PG Hitech City',
            description: 'Premium PG in IT hub with modern amenities and close to major tech companies.',
            address: 'HITEC City Road, Madhapur, Hyderabad, Telangana 500081',
            city: 'Hyderabad',
            locality: 'Hitech City',
            latitude: 17.4435,
            longitude: 78.3772,
            genderType: 'Male',
            thumbnailImage: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1555854877-bab0e564b8d5',
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457'
            ]),
            startingPrice: 15000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Gym', 'Laundry', 'Parking']),
            virtualTourUrl: 'https://example.com/virtual-tour/23',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543231',
            managerName: 'Srinivas Reddy',
            rating: 4.6,
            totalReviews: 83,
            isAvailable: true,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Royal Gardens PG Gachibowli',
            description: 'Luxury PG with swimming pool and sports facilities in Gachibowli.',
            address: 'Financial District, Gachibowli, Hyderabad, Telangana 500032',
            city: 'Hyderabad',
            locality: 'Gachibowli',
            latitude: 17.4399,
            longitude: 78.3489,
            genderType: 'Female',
            thumbnailImage: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457'
            ]),
            startingPrice: 17000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Gym', 'Laundry', 'Parking', 'Balcony']),
            virtualTourUrl: 'https://example.com/virtual-tour/24',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543232',
            managerName: 'Kavitha Sharma',
            rating: 4.8,
            totalReviews: 91,
            isAvailable: true,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Smart Living Kondapur',
            description: 'Affordable PG near Botanical Gardens with good connectivity to IT corridor.',
            address: 'Kondapur Main Road, Kondapur, Hyderabad, Telangana 500084',
            city: 'Hyderabad',
            locality: 'Kondapur',
            latitude: 17.4610,
            longitude: 78.3643,
            genderType: 'Unisex',
            thumbnailImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267',
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365'
            ]),
            startingPrice: 12000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Laundry', 'Parking']),
            virtualTourUrl: null,
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543233',
            managerName: 'Venkat Rao',
            rating: 4.4,
            totalReviews: 64,
            isAvailable: true,
            createdAt: new Date('2024-03-15').toISOString(),
        },
        {
            name: 'Heritage Stays Banjara Hills',
            description: 'Premium PG in upscale Banjara Hills with personalized services and fine dining.',
            address: 'Road No 12, Banjara Hills, Hyderabad, Telangana 500034',
            city: 'Hyderabad',
            locality: 'Banjara Hills',
            latitude: 17.4239,
            longitude: 78.4738,
            genderType: 'Female',
            thumbnailImage: 'https://images.unsplash.com/photo-1540518614846-7eded433c457',
            images: JSON.stringify([
                'https://images.unsplash.com/photo-1540518614846-7eded433c457',
                'https://images.unsplash.com/photo-1556020685-ae41abfc9365',
                'https://images.unsplash.com/photo-1502672260066-6bc2557e94b1',
                'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af'
            ]),
            startingPrice: 20000,
            amenities: JSON.stringify(['AC', 'WiFi', 'Food', 'Gym', 'Laundry', 'Parking', 'Balcony']),
            virtualTourUrl: 'https://example.com/virtual-tour/26',
            cancellationPolicy: 'Free cancellation up to 7 days before check-in',
            refundPolicy: '100% refund for cancellation 7+ days before',
            managerPhone: '+919876543234',
            managerName: 'Swathi Menon',
            rating: 4.9,
            totalReviews: 96,
            isAvailable: true,
            createdAt: new Date('2024-01-08').toISOString(),
        },
    ];

    const values = sampleProperties.map((p: any) => ({
        ...p,
        createdAt: typeof p.createdAt === 'string' ? new Date(p.createdAt) : p.createdAt,
    }));

    await db.insert(properties).values(values);
    
    console.log('✅ Properties seeder completed successfully - 25 diverse properties created across major Indian cities');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});